version: 2

sources: 
  - name: staging
    database: airflow # database
    schema: public # schema
    tables: 
      - name: github_data
  
models:
  - name: staging_github_data
    description: "data in staging layer is guaranteed to not redundant and not duplicate"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
      - name: type
        tests:
          - not null
      - name: actor
        tests:
          - not null
      - name: repo
        tests:
          - not null
      - name: payload
        tests:
          - not null
      - name: public
        tests:
          - not null
      - name: created_at
        tests:
          - not null
      - name: org
        tests:
          - not null